### ISSUE TITLE
[Feat] Prop for aria-label property

### ISSUE THREAD

**Issue by nellysbr** [tjtanjin/react-chatbotify-docs#2]
**Is your feature request related to a problem? Please describe.**

Yes, because without this feature, the chatbot doesn't comply with accessibility metrics.

**Describe the solution you'd like**

It is necessary to create a prop where I can place text in the aria-label property. Since the bot avatar is a button and has an image without text, this property becomes mandatory for accessibility purposes. The <button></button> can have an aria-label by default; however, it would be interesting to make this property editable to allow for translation into other languages.

**Describe alternatives you've considered**
There's no alternatives for this one. 

**Additional context**
![image](https://github.com/tjtanjin/react-chatbotify-docs/assets/73605907/20e23f25-96dc-47f7-9a89-ed8a99eb6b1e)

**Comment by tjtanjin** [comment]
A default value for `aria-label` has been added and will be available in v1.6.1. There's no clean way to allow customizations of attributes at the moment but it could be worth re-looking at this sometime down the road 😊
