### ISSUE TITLE
[Task] Centralize check marks in table for supported browsers

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-docs#5]
**Description:**
The check marks on the table in this page are not centered: https://react-chatbotify.com/docs/compatibility/supported_browsers

It would be nice to centralize it.

**Comment by tjtanjin** [comment]
> /attempt

I assume you're keen for this task :P Go for it!

**Comment by kk7188048** [comment]
I have done the required changes but can you tell me how to start the script, its kina of confusing.

**Comment by tjtanjin** [comment]
> I have done the required changes but can you tell me how to start the script, its kina of confusing.

You can open a pull request with your changes, what script are you referring to? 😅

**Comment by kk7188048** [comment]
i mean locally in my pc.

**Comment by tjtanjin** [comment]
> i mean locally in my pc.

Assuming you've done `npm install` you can do `npm run start` and visit http://localhost:3000.

**Comment by tjtanjin** [comment]
Completed with #6
